// SOH [WASM] Shared by index.html and host.html: the parts of a host page that are not about
// where the files come from. An embedder does not need this file; see HOST-API.md.
'use strict';

var SohHostPage = (() => {
  function show(statusEl, text) {
    statusEl.style.display = '';
    statusEl.textContent = text;
  }

  // --- Memory trace ---------------------------------------------------------------------
  // A renderer crash ("Aw, Snap") takes the console with it, so samples are kept in
  // localStorage and reported on the next load. The wasm heap can grow to 2GB by default
  // (Emscripten's MAXIMUM_MEMORY); an allocation past that aborts the module. Enable with
  // ?memtrace, read the previous run's trail from the console after a crash.
  const TRACE_KEY = 'soh-memtrace';       // the run in progress
  const PREV_KEY  = 'soh-memtrace-prev';  // the last finished/crashed run, kept for reading

  function reportPreviousTrace() {
    // The finished run is moved to its own key rather than deleted, so it survives any
    // number of reloads and can be read back by hand at any time:
    //   JSON.parse(localStorage.getItem('soh-memtrace-prev'))
    // Only the next run with ?memtrace overwrites it.
    try {
      const live = localStorage.getItem(TRACE_KEY);
      if (live) localStorage.setItem(PREV_KEY, live);
      localStorage.removeItem(TRACE_KEY);
      const prev = JSON.parse(localStorage.getItem(PREV_KEY) || '[]');
      if (prev.length) {
        const last = prev[prev.length - 1];
        const peak = prev.reduce((m, s) => Math.max(m, s.heapMB), 0);
        console.warn(`memtrace: previous run ran ${last.t}s, ended at ${last.heapMB} MB, ` +
                     `peak ${peak} MB (cap 2048). Trail:`);
        console.table(prev);
      } else {
        console.warn('memtrace: no previous run recorded.');
      }
    } catch (e) { /* private mode, blocked storage: tracing is optional */ }
  }

  function startMemtrace(statusEl) {
    if (!new URLSearchParams(location.search).has('memtrace')) return;
    reportPreviousTrace();
    const started = Date.now();
    const trail = [];
    let lastTotalMB = null;
    setInterval(() => {
      const heap = Module.HEAPU8 ? Module.HEAPU8.buffer.byteLength : 0;
      if (!heap) return;
      const sample = {
        t: Math.round((Date.now() - started) / 1000),
        heapMB: Math.round(heap / 1048576),
        jsMB: performance.memory ? Math.round(performance.memory.usedJSHeapSize / 1048576) : null,
        totalMB: lastTotalMB, // whole renderer (wasm + JS + DOM + canvases); null unless cross-origin isolated
      };
      // performance.measureUserAgentSpecificMemory needs crossOriginIsolated and is async, so
      // it is requested here and lands in the next sample.
      if (self.crossOriginIsolated && performance.measureUserAgentSpecificMemory) {
        performance.measureUserAgentSpecificMemory()
          .then(m => { lastTotalMB = Math.round(m.bytes / 1048576); }, () => {});
      }
      trail.push(sample);
      if (trail.length > 600) trail.shift();   // ~10 min at 1Hz
      show(statusEl, `wasm heap ${sample.heapMB} MB` +
        (sample.jsMB !== null ? `   js ${sample.jsMB} MB` : '') +
        (sample.totalMB !== null ? `   total ${sample.totalMB} MB` : '') +
        `   (cap 2048 MB)`);
      try { localStorage.setItem(TRACE_KEY, JSON.stringify(trail)); } catch (e) {}
    }, 1000);
  }

  // --- Host files -----------------------------------------------------------------------
  // Writes Module.shipFiles (VFS path -> bytes, see HOST-API.md) into the filesystem during
  // preRun. soh.js carries Module.sohBuild, generated by CMake, which says whether this build
  // expects the page to supply oot.o2r and which paths are already packaged in soh.data. A
  // page must not write those: the package is unpacked after preRun and would collide.
  function writeHostFiles(statusEl) {
    const files = Module.shipFiles || {};
    const build = Module.sohBuild || { hostFiles: true, bakedFiles: ['/soh.o2r'] };
    if (build.hostFiles && !files['/oot.o2r']) {
      const msg = 'No game archive.\n\n' +
        'This build expects the page to supply oot.o2r (it was built with\n' +
        'SOH_WASM_HOST_FILES=ON). Set Module.shipFiles before loading soh.js:\n\n' +
        "  Module.shipFiles = { '/oot.o2r': bytes };\n\n" +
        'See soh/wasm/HOST-API.md, or host.html for a worked example.';
      show(statusEl, msg);
      console.error(msg);
      throw new Error('shipFiles: no /oot.o2r provided');
    }
    let written = 0;
    for (const [path, bytes] of Object.entries(files)) {
      if (build.bakedFiles.includes(path)) {
        console.warn(`shipFiles: ${path} is already packaged in this build; ignoring the page's copy`);
        continue;
      }
      const dir = path.slice(0, path.lastIndexOf('/'));
      if (dir) Module.FS.mkdirTree(dir);
      Module.FS.writeFile(path, bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes));
      written++;
    }
    console.log(`shipFiles: wrote ${written} file(s) into the VFS`);
  }

  return { show, startMemtrace, writeHostFiles };
})();
